Create new network-with-nat module.
terraform-alicloud-modules/terraform-alicloud-network-with-nat pull request #1
Opened 2020-02-28 11:55 UTC by zql-tqy

2020-02-28 13:04 UTC, Rich-yi commented on README-CN.md
> +      snat_ip = concat(module.vpc-nat.this_eip_ips, [""])[0]
这些应该要写个参数进去吧

2020-02-28 13:04 UTC, Rich-yi commented on outputs.tf
> +  description = "The VPC name"
标点

2020-02-28 13:04 UTC, Rich-yi commented on variables.tf
> +  description = "Internet charge type of the EIP, Valid values are `PayByBandwidth`, `PayByTraffic`. "
`改成'

2020-03-01 01:53 UTC, xiaozhu36 requested changes

2020-03-01 01:53 UTC, xiaozhu36 commented on main.tf
> +  use_num_suffix      = var.use_num_suffix
use_num_suffix 直接写死为 true

2020-03-01 01:53 UTC, xiaozhu36 commented on README-CN.md
> +* [snat_entry](https://www.terraform.io/docs/providers/alicloud/r/snat.html)
这几个格式统一下VPC，Nat Gateway，Snat Entry 等

2020-03-01 01:53 UTC, xiaozhu36 commented on README-CN.md
> +  cbp_bindwidth = 10
bindwidth拼错了吧

2020-03-01 01:53 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  source  = "../../../terraform-alicloud-security-group"
地址不对吧

2020-03-01 01:53 UTC, xiaozhu36 commented on main.tf
> +  create_vpc = var.existing_vpc_id != "" ? var.use_existing_vpc : var.create_vpc
create_vpc =  var.use_existing_vpc ？ false : var.create_vpc

2020-03-01 01:53 UTC, xiaozhu36 commented on main.tf
> +  vpc_id              = var.vpc_id != "" ? var.vpc_id : module.vpc.vpc_id
需要有单独的vpc——id，我理解直接用existing_vpc_id

2020-03-01 01:53 UTC, xiaozhu36 commented on main.tf
> +  source                  = "terraform-alicloud-modules/eip/alicloud"
这个地方不用eip的module，直接用nat的module。里面已经支持了eip的创建和绑定

2020-03-01 01:53 UTC, xiaozhu36 commented on variables.tf
> +variable "use_num_suffix" {
这个不用暴露，直接设置为 true

2020-03-01 01:53 UTC, xiaozhu36 commented on variables.tf
> +variable "name" {
这个name加个nat的前缀。
这个module再根据 https://github.com/terraform-alicloud-modules/terraform-alicloud-multi-zone-infrastructure-with-ots 完善下，包括逻辑，参数命名啥的

2020-03-01 06:16 UTC, xiaozhu36 requested changes

2020-03-01 06:16 UTC, xiaozhu36 commented on variables.tf
> +variable "ratio" {
cbp_ratio

2020-03-01 06:16 UTC, xiaozhu36 commented on variables.tf
> +variable "nat_gateway_id" {
nat_gateway_id这个不需要，直接使用本module创建的

2020-03-01 06:16 UTC, xiaozhu36 commented on variables.tf
> +variable "snat_table_id" {
snat_table_id这个不需要，直接使用本module创建的

2020-03-01 06:16 UTC, xiaozhu36 commented on variables.tf
> +variable "external_ip" {
dnat_ external_ip

2020-03-01 06:16 UTC, xiaozhu36 commented on variables.tf
> +variable "entries" {
dnat_entries

2020-03-01 06:16 UTC, xiaozhu36 commented on variables.tf
> +variable "period" {
nat_period

2020-03-01 06:16 UTC, xiaozhu36 commented on variables.tf
> +variable "instance_charge_type" {
nat_ instance_charge_type

2020-03-01 06:16 UTC, xiaozhu36 commented on variables.tf
> +variable "specification" {
nat_specification

2020-03-01 06:16 UTC, xiaozhu36 commented on variables.tf
> +variable "existing_nat_gateway_id" {
existing_nat_gateway_id  和 use_existing_nat_gateway 都不需要，直接创建新的

2020-03-01 06:16 UTC, xiaozhu36 commented on variables.tf
> +variable "name" {
nat_name

2020-03-01 08:30 UTC, xiaozhu36 requested changes

2020-03-01 08:30 UTC, xiaozhu36 commented on main.tf
> +  vpc_description = "A new VPC created by Terrafrom module terraform-alicloud-vpc"
A new VPC created by Terrafrom module terraform-alicloud-network-with-nat
其他的也是

2020-03-01 08:30 UTC, xiaozhu36 commented on README.md
> +      internal_ip   = "m-2ze87razmgndj8un****"
这个应该是ip 地址把，不是 镜像id

2020-03-01 08:30 UTC, xiaozhu36 commented on variables.tf
> +  description = "Whether to create vpc. If false, you can specify an existing vpc by setting 'vpc_id'."
最后应该是 existing_vpc_id

2020-03-01 08:30 UTC, xiaozhu36 commented on variables.tf
> +  description = "The tags used to launch a new vpc. Before 1.5.0, it used to retrieve existing VPC."
Before 1.5.0, it used to retrieve existing VPC. 这句话去掉

2020-03-01 08:30 UTC, xiaozhu36 commented on variables.tf
> +  description = "Whether to create nat gateway. If false, you can specify an existing nat gateway by setting 'nat_gateway_id'."
If false, you can specify an existing nat gateway by setting 'nat_gateway_id' 这句话去掉

2020-03-01 08:30 UTC, xiaozhu36 commented on variables.tf
> +  type        = bool
If true, the 'number_of_dnat_eip' or  'number_of_snat_eip'  should not be empty.

2020-03-01 08:30 UTC, xiaozhu36 commented on variables.tf
> +  default     = "TF-EIP-for-Nat"
默认值：tf-module-network-with-nat

2020-03-01 08:30 UTC, xiaozhu36 commented on variables.tf
> +  default     = "terraform-alicloud-nat-gateway"
默认值：tf-module-network-with-nat

2020-03-01 08:30 UTC, xiaozhu36 commented on variables.tf
> +  default     = "TF-VSwitch"
默认值：tf-module-network-with-nat

2020-03-01 08:30 UTC, xiaozhu36 commented on variables.tf
> +  default     = "TF-VPC"
默认值：tf-module-network-with-nat

2020-03-01 08:44 UTC, xiaozhu36 approved these changes

2020-03-01 08:44 UTC, merged